carousel:
    images: aerosmith.jpg, iron maiden.jpg, madonna.jpg, metallica.jpg, queen.jpg,
        rolling stones.webp
    refresh-cron: 0 */10 * * * *
logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
mvc:
    hiddenmethod:
        filter:
            enabled: true
servlet:
    multipart:
        max-file-size: 1MB
        max-request-size: 5MB
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 12345
        url: jdbc:mysql://localhost:3306/softuni_music_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
